# MCU8 Bootloader Configuration

# Configuration Data Specific to the generated bootloader
[bootloader]
IMAGE_FORMAT_VERSION = "0.3.0"
PAGE_ERASE_KEY = 0xAA55
PAGE_WRITE_KEY = 0xAA55
PAGE_READ_KEY = 0x0000
BYTE_WRITE_KEY = 0xAA55
DEVICE_ID = 0x00007920
WRITE_BLOCK_SIZE = 0x100
FLASH_START = 0x00002000
FLASH_END = 0x010000
EEPROM_START = 0x380000
EEPROM_END = 0x3801FF
CONFIG_START = 0x300000
CONFIG_END = 0x30000B
ARCH = "PIC18"
VERIFICATION = "Check Reset Vector"

# Data needed by the host
[host]
coms = "UART"