# MCU8 Bootloader Configuration

# Configuration Data Specific to the generated bootloader
[bootloader]
IMAGE_FORMAT_VERSION = "0.3.0"
PAGE_ERASE_KEY = 0xAA55
PAGE_WRITE_KEY = 0xAA55
PAGE_READ_KEY = 0x00
BYTE_WRITE_KEY = 0xAA55
DEVICE_ID = 0x00007920
WRITE_BLOCK_SIZE = 0x100
FLASH_START = 0x00002000
FLASH_END = 0x010000
EEPROM_START = 0x380000
EEPROM_END = 0x000000
CONFIG_START = 0x300018
CONFIG_END = 0x30001C
ARCH = "PIC18"
VERIFICATION = "CRC-32"

# Data needed by the host
[host]